# Generated by Django 3.0.7 on 2020-06-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulting_service', models.CharField(max_length=200)),
                ('consulting_description', models.TextField(blank=True)),
                ('property_management', models.CharField(max_length=200)),
                ('property_description', models.TextField(blank=True)),
                ('renting_selling', models.CharField(max_length=200)),
                ('r_s_description', models.TextField(blank=True)),
            ],
        ),
    ]
